#/bin/sh
#PBS -V
#PBS -V
#PBS -l walltime=6:00:00
#PBS -M pmjindal@gmail.com
#PBS -m abe
#PBS -l nodes=1:ppn=20
#PBS -l mem=50gb
#PBS -q gpu

HOME_DIR=/home/du4/19CS30033
WORK_DIR=$HOME_DIR/lotteryFL_cell

module load anaconda3
source activate $HOME_DIR/anaconda3/envs/CELL
cd $WORK_DIR
wandb offline

python main.py --rounds 100 --n_classes 3 --n_clients 20 --n_samples 200 --exp_name CELL_TEST --frac_clients_per_round 0.5 --server_prune True --server_prune_freq 13 --server_prune_step 0.1

